version: "3.8"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres12:
    container_name: postgres12
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: msvc_cursos
      POSTGRES_PASSWORD: sasa
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    image: alidi10/usuarios:latest
#    build: 
#      context: ./
#      dockerfile: ./springboot-msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./springboot-msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    image: alidi10/cursos:latest
#   build: 
#      context: ./
#      dockerfile: ./springboot-msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: 
      - ./springboot-msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres12
      - msvc-usuarios
    restart: always
volumes:
  data-mysql:
    name: data-mysql
    external: true
  data-postgres:
    name: data-postgres
    external: true
networks:
  spring:
    name: spring
    external: true